### ISSUE TITLE
Error while processing privacy data

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-local_recompletion#191]
When accepting deletion requests we are now getting these....

```
Exception occurred while calling local_recompletion\privacy\provider::delete_data_for_user.
This means that plugin local_recompletion did not complete the processing of data. The following exception information may be passed on to the plugin developer:

ERROR: Incorrect number of query parameters. Expected 2, got 0.


#0 /var/www/html/moodle/lib/dml/mysqli_native_moodle_database.php(1815): moodle_database->fix_sql_params()
#1 /var/www/html/moodle/local/recompletion/classes/privacy/provider.php(476): mysqli_native_moodle_database->delete_records_select()
#2 /var/www/html/moodle/lib/moodlelib.php(7821): local_recompletion\privacy\provider::delete_data_for_user()
#3 /var/www/html/moodle/privacy/classes/manager.php(578): component_class_callback()
#4 /var/www/html/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#5 /var/www/html/moodle/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback()
#6 /var/www/html/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(151): core_privacy\manager->delete_data_for_user()
#7 /var/www/html/moodle/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#8 /var/www/html/moodle/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#9 /var/www/html/moodle/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#10 /var/www/html/moodle/admin/cli/cron.php(186): core\cron::run_main_process()
#11 {main}
```

I haven't investigated at all (yet).

**Comment by danmarsden** [comment]
Thanks Howard! - I've just pushed a fix into the branch here, I'll look to push it into the plugins db soon,
